* Gamify

Gamify is an Emacs package that will turn your ordinary, boring day-to-day Emacs experience into something awesome!
Well, not really... You can use it to track your soft and professional skills developement while keeping you motivated to do stuff such as your [[http://orgmode.org/][Org-Mode]] tasks and enhancing your productivity.

* Installation

You can use =use-package= together with =quelpa= to install Gamify directly from this repository:

#+begin_src emacs-lisp
(use-package quelpa)
(quelpa '(gamify :repo Idorobots/gamify-el :fetcher github))
#+end_src

Alternatively, copy all the =.el= files into a directory in your Emacs =load-path= and optionally =byte-compile-file= them.

* Customization

There are quite a few variables to tweak:
- =gamify-update-interval= - number of seconds between mode-line updates.
- =gamify-format= - format string used in the mode-line:
   =%T= - total exp point you own,
   =%XP= - "level-bar" percentage,
   =%xp= - focus stat percentage,
   =%Lc= - current level name,
   =%Ln= - next level name.
- =gamify-default-exp= - default base exp value used by =gamify-some-exp=.
- =gamify-default-exp-delta= - default exp delta used by =gamify-some-exp=.
- =gamify-stats-file= - file where Gamify should save your stats.
- =gamify-very-rusty-time= - time in seconds, when your skills are considered "very rusty".
- =gamify-rusty-time= - time in seconds, when your skills are considered "rusty".
- =gamify-stat-level= - an alist of exp values and level names for your stats. Defaults to Dwarf Fortress-esque skill set.
- =gamify-org-p= - tell Gamify wether to gamify your Org-Mode tasks, or not.
- =gamify-notification-function= - which function to use to send notifications.
- =gamify-notification-xp-icon-path= - what icon to use for notifications.

This list likely is not exhaustive. Just check the source, dang it!
